nutrient_management_system/articles/urls.py
from articles import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^(?P<pk>[0-9]+)/article/$', views.full_article, name='full_article'),
    url(r'^add/$', login_required(views.ArticleFormView.as_view()),
        name='add_article'),
    url(r'^(?P<pk>[0-9]+)/edit/',
        login_required(views.ArticleUpdate.as_view()),
        name='edit_article'),
    url(r'^(?P<pk>[0-9]+)/delete/',
        login_required(views.ArticleDelete.as_view()),
        name='delete_article')
]

nutrient_management_system/drop_a_note/urls.py
from django.conf.urls import url

from drop_a_note import views

app_name = 'contact'

urlpatterns = [
    url(r'^$', views.ContactFormView.as_view(), name='contact'),
    url(r'^feedbacks/', views.feedbacks, name='feedbacks'),
]

nutrient_management_system/home/urls.py
from django.conf.urls import url

from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home')
]

nutrient_management_system/nutrient_management_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/', include('about_us.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^contact/', include('drop_a_note.urls')),
    url(r'^info/', include('nutrients_info.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^home/', include('home.urls'))
]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

nutrient_management_system/home/models.py
from django.db import models

nutrient_management_system/home/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

nutrient_management_system/home/views.py
from django.apps import apps
from django.shortcuts import render
from django.views import View
from home.forms import UserForm


def home(request):
    article_model = apps.get_model('articles.Article')
    articles = article_model.objects.all().order_by('-id')[:3]
    drop_a_note_model = apps.get_model('drop_a_note.Note')
    notes = drop_a_note_model.objects.all().order_by('-id')[:3]
    return render(request, 'index.html',
                  {'articles': articles, 'notes': notes})


class UserFormView(View):
    form_class = UserForm
    template_name = 'registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {form: form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

nutrient_management_system/home/templates/index.html
{% extends 'base.html' %}

{% block body %}


<div class="fh5co-hero"
     style="background-image: url('https://static.pexels.com/photos/8066/fruits-market-colors.jpg');"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div
            class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
          <div class="fh5co-intro fh5co-table-cell">
            <h1 class="text-center">Nutri-Health</h1>
            <p>
              A Nutrition Management Website
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-section">
    <div class="container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <div class="text-center"><h2>Little about website</h2></div>
          <p>Eating a balanced diet is vital for good health and wellbeing.
            Food provides our bodies with the energy, protein, essential fats,
            vitamins and minerals to live,
            grow and function properly. We need a wide variety of different
            foods to provide
            the right amounts of nutrients for good health. This website
            provide you data to keep your diet
            balance, You can get detail of all nutrient, seasonal fruits and
            food, Geographical fruits and food. And most important things
            that is article on topic relative to health, nutrition, diet etc
            .</p>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </div>

  <div class="fh5co-parallax"
       style="background-image: url('http://www.danos.gr/wp-content/uploads/2014/04/ARTICLES.jpg');height: 300px; margin: auto;"
       data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div
            class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
          <div class="fh5co-intro fh5co-table-cell">
            <h1 class="text-center" style="margin-top: -180px;">
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-section">
    <div class="container">
      <div class="row">

        <div class="col-md-12">
          <div class="text-center"><h2></h2></div>
          <span><a href="{% url 'articles:add_article' %}">Add New</a></span>
          <br><br>
          {% for article in articles %}
          <div class="fh5co-text article-box-home">
            <div class="text-center"><h1>{{ article.title }}</h1>
              <hr>
            </div>
            <span><small>{{ article.date }}</small></span><span
              style="float: right;">
              <small>Published by:</small><br>
            <small>{{ article.publisher }}</small>
          </span>
            <div class="article-content">
              {{ article.content }}
            </div>
            {% if request.user.id == article.user.id %}
            <span><small><a
                href="{% url 'articles:edit_article' article.id %}">Edit</a></small></span>
            |<span><small><a
              href="{% url 'articles:delete_article' article.id %}">Delete</a></small></span>
            <span style="float: left;">
              {% endif %}
              <small><a href="{% url 'articles:full_article' article.id %}">Read More</a></small>
              </span>
          </div>
          {% endfor %}
          <div><a href="{% url 'articles:articles' %}">SEE
            MORE</a></div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-parallax"
       style="background-image: url('https://ak0.picdn.net/shutterstock/videos/973990/thumb/1.jpg');height: 300px; margin: auto;">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div
            class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
          <div class="fh5co-intro fh5co-table-cell">
            <h1 class="text-center" style="margin-top: -180px;">
              Feedback</h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% for note in notes %}
          <div class="fh5co-text article-box-home">
            <div class="text-center">
              <h1>
                <div class="feedback-content-home ">
                  {{ note.note }}
                </div>
              </h1>
              <hr>
            </div>
            <div class="float-right">
              <small>Published by:</small>
              <br>
              <small>{{ note.name }}</small>
              <br>
              <small>{{ note.email }}</small>
            </div>
          </div>
          {% endfor %}
          <div class="float-right"><a href="{% url 'contact:feedbacks' %}">SEE
            MORE</a></div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

nutrient_management_system/home/templates/registration_form.html
{% extends 'base.html' %}

{% block body %}


{% endblock %}