nutrient_management_system/about_us/urls.py
from django.conf.urls import url
from about_us import views

app_name = 'about_us'

urlpatterns = [
    url(r'^$', views.about, name='about')
]

nutrient_management_system/articles/urls.py
from articles import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.articles, name='articles'),
    url(r'^(?P<pk>[0-9]+)/article/$', views.full_article, name='full_article'),
    url(r'^add/$', login_required(views.ArticleFormView.as_view()),
        name='add_article'),
    url(r'^(?P<pk>[0-9]+)/edit/',
        login_required(views.ArticleUpdate.as_view()),
        name='edit_article'),
    url(r'^(?P<pk>[0-9]+)/delete/',
        login_required(views.ArticleDelete.as_view()),
        name='delete_article')
]

nutrient_management_system/drop_a_note/urls.py
from django.conf.urls import url

from drop_a_note import views

app_name = 'contact'

urlpatterns = [
    url(r'^$', views.ContactFormView.as_view(), name='contact'),
    url(r'^feedbacks/', views.feedbacks, name='feedbacks'),
]

nutrient_management_system/home/urls.py
from django.conf.urls import url

from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home')
]

nutrient_management_system/nutrient_management_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/', include('about_us.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^contact/', include('drop_a_note.urls')),
    url(r'^info/', include('nutrients_info.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^home/', include('home.urls'))
]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

nutrient_management_system/users/urls.py
from django.conf.urls import url

from users import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.users, name='user'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout')
]

nutrient_management_system/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content=""/>
  <meta property="og:image" content=""/>
  <meta property="og:url" content=""/>
  <meta property="og:site_name" content=""/>
  <meta property="og:description" content=""/>
  <meta name="twitter:title" content=""/>
  <meta name="twitter:image" content=""/>
  <meta name="twitter:url" content=""/>
  <meta name="twitter:card" content=""/>
  <title>{% block title %}{% endblock %}</title>

  <link
      href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700'
      rel='stylesheet' type='text/css'>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div id="fh5co-wrap">
  <header id="fh5co-header">
    <div class="container">
      <nav class="fh5co-main-nav">
        <ul>
          <li class="fh5co-active"><a
              href="{% url 'home:home' %}"><span>Home</span></a>
          </li>
          <li><a
              href="{% url 'nutrients_info:info' %}"><span>Nutrients_Info</span></a>
          </li>
          <li>
            <a href="{% url 'articles:articles' %}"><span>Articles</span></a>
          </li>
          <li>
            <a
                href="{% url 'about_us:about' %}"><span>About</span></a>
          </li>
          <li>
            <a href="{% url 'contact:contact' %}"><span>Leave A Note</span></a>
          </li>
          <li>
            {% if request.user.username != '' %}
              <a href="{% url 'users:user_logout' %}"><span>
                {{ request.user.username }}</span></a>
            {% else %}
              <a href="{% url 'users:register' %}"><span>
                Register/login</span></a>
            {% endif %}
          </li>
        </ul>
      </nav>
    </div>
  </header>

  {% block body %}
  {% endblock %}
</div>
<footer id="fh5co-footer">
  <div class="container">
    <div id="contact-box" class="row">
      <div class="col-sm-6">
        <div class="block">
          <h2>About US</h2>
          <ul class="address-block">
              <li>Nutri-Health is a one-stop nutrition management website who provide all detail of diet and disease due
                  to
                  lack of nutrient. It also provides the list of diet and health-related article. If you have any query
                  regarding
                  diet or nutrition management you
                  frequently ask any type question that admin provide you solution by the mail to you or update it on a
                  website.
            </li>
          </ul>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="block">
          <h2>Stop By For A visit</h2>
          <ul class="address-block">
            <li>
                <i class="fa fa-map-marker"></i>Address : RoomNo-1004, Block B, PDPU High Rise Hostel, &nbsp; &nbsp;&nbsp;&nbsp;
                Gandhinagar, Gujarat
            </li>
            <li>
                <i class="fa fa-envelope-o"></i>Email: 201552060@iiitvadoadara.ac.in <br> &nbsp; &nbsp;&nbsp;&nbsp;
                201552064@iiitvadodara.ac.in
            </li>
            <li>
                <i class="fa fa-phone"></i>Phone:+8347773419 <br> &nbsp; &nbsp;&nbsp;&nbsp;+8209875707
            </li>
          </ul>

          <ul class="social-icons">
            <li>
              <a href="#"><i class="fa fa-google"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-linkedin"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-pinterest"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-dribbble"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-behance"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li>
              <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</footer>

<script>
  /*$(document).ready(function () {
    $('.fh5co-main-nav li').click(function (event) {
      //remove all pre-existing active classes
      $('.fh5co-active').removeClass('fh5co-active');

      //add the active class to the link we clicked
      $(this).addClass('fh5co-active');

      //Load the content
      //e.g.
      //load the page that the link was pointing to
      // $('#content').load($(this).find(a).attr('href'));

      event.preventDefault();
    });
  });*/
</script>
</body>
</html>

nutrient_management_system/templates/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="text-danger small">{{ field.errors }}</div>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

nutrient_management_system/templates/generic_form.html
{#{% extends 'base.html' %}#}
{#{% block title %} Register {% endblock %}#}
{#{% block body %}#}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{#{% endblock %}#}

nutrient_management_system/templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Simple &mdash; Free HTML5 Bootstrap Website Template by
        FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Free HTML5 Website Template by FreeHTML5.co"/>
    <meta name="keywords"
          content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive"/>
    <meta name="author" content="FreeHTML5.co"/>

    <!--
      //////////////////////////////////////////////////////

      FREE HTML5 TEMPLATE
      DESIGNED & DEVELOPED by FreeHTML5.co

      Website: 		http://freehtml5.co/
      Email: 			info@freehtml5.co
      Twitter: 		http://twitter.com/fh5co
      Facebook: 		https://www.facebook.com/fh5co

      //////////////////////////////////////////////////////
       -->

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">

    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,300,600,400italic,700'
          rel='stylesheet' type='text/css'>

    <!-- Animate.css -->
    <link rel="stylesheet" href="css/animate.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="css/magnific-popup.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="css/bootstrap.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="css/icomoon.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="css/style.css">

    <!-- Modernizr JS -->
    <script src="js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

</head>
<body>

<div id="fh5co-wrap">
    <header id="fh5co-header">
        <div class="container">
            <nav class="fh5co-main-nav">
                <ul>
                    <li class="fh5co-active"><a
                            href="index.html"><span>Home</span></a></li>
                    <li><a href="services.html"><span>Services</span></a></li>
                    <li>
                        <a href="../about_us/templates/about.html"><span>About</span></a>
                    </li>
                    <li><a href="../drop_a_note/templates/contact.html"><span>Contact</span></a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <div class="fh5co-hero" style="background-image: url(images/hero_1.jpg);"
         data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                    <div class="fh5co-intro fh5co-table-cell">
                        <h1 class="text-center">Make simple and functional
                            templates</h1>
                        <p>Made with love by the fine folks at <a
                                href="http://freehtml5.co">FreeHTML5.co</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="fh5co-section">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <h2>Creative Design</h2>
                    <p>Even the all-powerful Pointing has no control about the
                        blind texts it is an almost unorthographic life One day
                        however a small line of blind text by the name of Lorem
                        Ipsum decided to leave for the far World of Grammar.
                        The Big Oxmox advised her not to do so, because there
                        were thousands of bad Commas, wild Question Marks and
                        devious Semikoli, but the Little Blind Text didn’t
                        listen.</p>
                </div>
                <div class="col-md-7">
                    <img src="images/hero_1.jpg"
                         alt="Free HTML5 by FreeHTML5.co"
                         class="img-responsive">
                </div>
            </div>
        </div>
    </div>

    <div class="fh5co-parallax"
         style="background-image: url(images/hero_2.jpg);"
         data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                    <div class="fh5co-intro fh5co-table-cell">
                        <h1 class="text-center">Keep it simple</h1>
                        <p>Made with love by the fine folks at <a
                                href="http://freehtml5.co">FreeHTML5.co</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fh5co-section">
        <div class="container">

            <div class="row">
                <div class="col-md-6">
                    <div class="fh5co-feature animate-box"
                         data-animate-effect="fadeInLeft">
                        <div class="fh5co-icon">
                            <i class="icon-strategy"></i>
                        </div>
                        <div class="fh5co-text">
                            <h3>Strategy</h3>
                            <p>Far far away, behind the word mountains, far
                                from the countries Vokalia and Consonantia,
                                there live the blind texts. </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="fh5co-feature animate-box"
                         data-animate-effect="fadeInLeft">
                        <div class="fh5co-icon">
                            <i class="icon-telescope"></i>
                        </div>
                        <div class="fh5co-text">
                            <h3>Explore</h3>
                            <p>Far far away, behind the word mountains, far
                                from the countries Vokalia and Consonantia,
                                there live the blind texts. </p>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="fh5co-feature animate-box"
                         data-animate-effect="fadeInLeft">
                        <div class="fh5co-icon">
                            <i class="icon-circle-compass"></i>
                        </div>
                        <div class="fh5co-text">
                            <h3>Direction</h3>
                            <p>Far far away, behind the word mountains, far
                                from the countries Vokalia and Consonantia,
                                there live the blind texts. </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="fh5co-feature animate-box"
                         data-animate-effect="fadeInLeft">
                        <div class="fh5co-icon">
                            <i class="icon-tools"></i>
                        </div>
                        <div class="fh5co-text">
                            <h3>Expertise</h3>
                            <p>Far far away, behind the word mountains, far
                                from the countries Vokalia and Consonantia,
                                there live the blind texts. </p>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>


    <div class="fh5co-parallax"
         style="background-image: url(images/hero_3.jpg);"
         data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
                    <div class="fh5co-intro fh5co-table-cell">
                        <h1 class="text-center">Less is more</h1>
                        <p>Made with love by the fine folks at <a
                                href="http://freehtml5.co">FreeHTML5.co</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="fh5co-section">
        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-6">
                            <h2>Made With Love</h2>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <p>Even the all-powerful Pointing has no control about the
                        blind texts it is an almost unorthographic life One day
                        however a small line of blind text by the name of Lorem
                        Ipsum decided to leave for the far World of Grammar.
                        The Big Oxmox advised her not to do so, because there
                        were thousands of bad Commas, wild Question Marks and
                        devious Semikoli, but the Little Blind Text didn’t
                        listen.</p>
                </div>
                <div class="col-md-6">
                    <p>She packed her seven versalia, put her initial into the
                        belt and made herself on the way. When she reached the
                        first hills of the Italic Mountains, she had a last
                        view back on the skyline of her hometown
                        Bookmarksgrove, the headline of Alphabet Village and
                        the subline of her own road, the Line Lane.</p>
                </div>
            </div>

        </div>
    </div>

</div> <!-- END fh5co-wrap -->


<footer id="fh5co-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3>About Us</h3>
                <p>She packed her seven versalia, put her initial into the belt
                    and made herself on the way. When she reached the first
                    hills of the Italic Mountains.</p>
            </div>
            <div class="col-md-3 col-md-push-1">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Products</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-md-push-1">
                <h3>Follow Us</h3>
                <ul class="fh5co-social">
                    <li><a href="#"><i class="icon-twitter"></i>
                        <span>Twitter</span></a></li>
                    <li><a href="#"><i class="icon-facebook"></i> <span>Facebook</span></a>
                    </li>
                    <li><a href="#"><i class="icon-instagram"></i> <span>Instagram</span></a>
                    </li>
                    <li><a href="#"><i class="icon-google"></i> <span>Google Plus</span></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 fh5co-copyright text-center">
                <p>
                    <small>&copy; 2016 Free HTML5 Simple. All Rights
                        Reserved.
                    </small>
                    <small>Made with care by <a href="http://freehtml5.co/"
                                                target="_blank">FreeHTML5.co</a>
                        Demo Images: <a href="http://unsplash.com"
                                        target="_blank">Unsplash</a></small>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- jQuery -->
<script src="js/jquery.min.js"></script>
<!-- jQuery Easing -->
<script src="js/jquery.easing.1.3.js"></script>
<!-- Bootstrap -->
<script src="js/bootstrap.min.js"></script>
<!-- Waypoints -->
<script src="js/jquery.waypoints.min.js"></script>
<!-- Stellar -->
<script src="js/jquery.stellar.min.js"></script>
<!-- MAIN JS -->
<script src="js/main.js"></script>

</body>
</html>