nutrient_management_system/home/urls.py
from django.conf.urls import url

from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home')
]

nutrient_management_system/nutrient_management_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^about/', include('about_us.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^contact/', include('drop_a_note.urls')),
    url(r'^info/', include('nutrients_info.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^home/', include('home.urls'))
]
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

nutrient_management_system/users/urls.py
from django.conf.urls import url

from users import views

app_name = 'users'

urlpatterns = [
    url(r'^$', views.users, name='user'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout')
]

nutrient_management_system/users/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=50, default='users name')
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=100)

nutrient_management_system/users/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

nutrient_management_system/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.decorators.csrf import csrf_protect
from home.forms import UserForm
from users.forms import LoginForm


def users(request):
    print(str(request.user.username) + " Hi dear u")
    return render(request, 'services.html')


class UserFormView(View):
    form_class = UserForm
    template_name = 'services.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            print(username + ' ' + password)

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('home:home')
        return render(request, self.template_name, {'form': form})


@csrf_protect
def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print(username + "  " + password)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:home')
        return HttpResponse("invalid credentials")
    else:
        form = LoginForm()
        return render(request, 'user_login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home:home')

nutrient_management_system/users/templates/registration_form.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}
{% block body %}
    <br><br><br><br>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

nutrient_management_system/users/templates/services.html
{% extends 'base.html' %}

{% block body %}
  <div class="fh5co-hero"
       style="background-image: url('http://www.nationalwillsafe.co.uk/wp-content/uploads/2015/03/Register.jpg');"
       data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div
            class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
          <div class="fh5co-intro fh5co-table-cell">
            <h1 class="text-center"></h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-section">
    <div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          {% include 'generic_form.html' %}
          <h3>Already Registered!! <a
              href="{% url 'users:user_login' %}">Login</a></h3>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </div>
{% endblock %}

nutrient_management_system/users/templates/user_login.html
{% extends 'base.html' %}

{% block body %}
  <div class="fh5co-hero"
       style="background-image: url('https://www.dialog-direct.com/cms/wp-content/uploads/2015/08/keyboard2.jpg');"
       data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div
            class="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-center fh5co-table">
          <div class="fh5co-intro fh5co-table-cell">
            <h1 class="text-center"></h1>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="fh5co-section">
    <div class="container">

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          {% include 'generic_form.html' %}
          <h3>Not Registered!! <a href="{% url 'users:register' %}">Sign Up</a></h3>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </div>
{% endblock %}